- framework: vue
  nickname: vue
  componentsFilesPaths: src/vue/components
- framework: react
  nickname: react
  componentsFilesPaths: src/react/components
- framework: preact
  nickname: preact
  componentsFilesPaths: src/preact/components
- framework: lit
  nickname: lit
  componentsFilesPaths: src/lit/components
- framework: svelte
  nickname: svelte
  componentsFilesPaths: src/svelte/components
- framework: solid-js
  nickname: solid
  componentsFilesPaths: src/solid/components
